#! /usr/bin/python

################################################################################
#    \file   SConscript
#    \author Gregory Diamos <solusstultus@gmail.com>
#    \date   June 13, 2015
#    \brief  The SCons program build script for lucius
################################################################################


Import('env')

lucius_libs = env['LUCIUS_LIBS']

programs = []

programs.append(env.Program('lucius-classifier', \
    ['tools/lucius-classifier.cpp'], LIBS=lucius_libs))

programs.append(env.Command("lucius-train-model.py",
    "tools/lucius-train-model.py", Copy("$TARGET", "$SOURCE")))

programs.append(env.Command("luciusgraphing.py",
    "tools/lucius-graph-training.py", Copy("$TARGET", "$SOURCE")))

programs.append(env.Command("lucius-graph-training.py",
    "tools/lucius-graph-training.py", Copy("$TARGET", "$SOURCE")))

programs.append(env.Command("__init__.py", "tools/lucius-graph-training.py", Touch("$TARGET")))

programs.append(env.Program('lucius-make-dataset', \
    ['tools/lucius-make-dataset.cpp'], LIBS=lucius_libs))

programs.append(env.Program('test-classifier', \
    ['engine/test/test-classifier.cpp'], LIBS=lucius_libs))

programs.append(env.Program('test-mnist', \
    ['engine/test/test-mnist.cpp'], LIBS=lucius_libs))

programs.append(env.Program('test-bracket-matching', \
    ['engine/test/test-bracket-matching.cpp'], LIBS=lucius_libs))

programs.append(env.Program('test-ctc-cpu', \
    ['matrix/test/test-ctc-cpu.cpp'], LIBS=lucius_libs))

programs.append(env.Program('test-ctc-operations', \
    ['matrix/test/test-ctc-operations.cpp'], LIBS=lucius_libs))

programs.append(env.Program('test-matrix', \
    ['matrix/test/test-matrix.cpp'], LIBS=lucius_libs))

programs.append(env.Program('test-matrix-vector', \
    ['matrix/test/test-matrix-vector.cpp'], LIBS=lucius_libs))

programs.append(env.Program('test-model', \
    ['model/test/test-model.cpp'], LIBS=lucius_libs))

#programs.append(env.Program('test-lucius-visualization', \
#    ['visualization/test/test-lucius-visualization.cpp'], LIBS=lucius_libs))

programs.append(env.Program('test-memory', \
    ['parallel/test/test-memory.cpp'], LIBS=lucius_libs))

programs.append(env.Program('test-lucius-display', \
    ['video/test/test-display.cpp'], LIBS=lucius_libs))

programs.append(env.Program('test-lucius-audio', \
    ['audio/test/test-audio.cpp'], LIBS=lucius_libs))

#programs.append(env.Program('test-lucius-performance', \
#    ['network/test/test-neuralnetwork-performance.cpp'], LIBS=lucius_libs))

programs.append(env.Program('test-gradient', \
    ['network/test/test-gradient-check.cpp'], LIBS=lucius_libs))

programs.append(env.Program('test-convolutional-gradient', \
    ['network/test/test-convolutional-gradient-check.cpp'], LIBS=lucius_libs))

programs.append(env.Program('test-subgraph', \
    ['network/test/test-subgraph.cpp'], LIBS=lucius_libs))

programs.append(env.Program('test-linear-regression', \
    ['network/test/test-linear-regression.cpp'], LIBS=lucius_libs))

programs.append(env.Program('test-optimizer', \
    ['optimizer/test/test-optimizer.cpp'], LIBS=lucius_libs))

Return('programs')


