#! /usr/bin/python

################################################################################
#    \file   SConscript
#    \author Gregory Diamos <solusstultus@gmail.com>
#    \date   Saturday August 10, 2013
#    \brief  The SCons master build script for the image classifier
################################################################################

def toSharedObject(filename):
    (root, ext) = os.path.splitext(str(filename))
    return root + '.os'

# set environment variables
lucious_args = ARGUMENTS
lucious_cmd_line_targets = COMMAND_LINE_TARGETS
lucious_path_to_root_dir = ".."

# try to import an environment
exec open(lucious_path_to_root_dir + "/scripts/which.py")
env = BuildEnvironment()
env['LUCIOUS_PATH'] = Dir('.').abspath

env['path_to_root_dir'] = os.path.abspath(lucious_path_to_root_dir)

# find all source files in the source tree
directories = ['lucious/driver', 'lucious/util', 'lucious/engine',
    'lucious/matrix', 'lucious/model', 'lucious/network',
    'lucious/optimizer', 'lucious/parallel', 'lucious/video', 'lucious/visualization',
    'lucious/database', 'lucious/input', 'lucious/results']

source_directories = [os.path.join(i, 'implementation') for i in directories]
cuda_source_directories = [os.path.join(i, 'cuda-implementation') for i in directories]
extensions = ['*.cpp']

sources = []
for dir in source_directories:
    for ext in extensions:
        regexp = os.path.join(dir, ext)
        sources.extend(env.Glob(regexp))

for dir in cuda_source_directories:
    for ext in extensions:
        regexp = os.path.join(dir, '*.cu')
        cuda_sources = env.Glob(regexp)
        for cuda_source in cuda_sources:
            sources.append(env.CUDASharedObject(cuda_source))

# create the library
liblucious = env.SharedLibrary('lucious', sources, LIBS=env['EXTRA_LIBS'])
lucious_libs = ['lucious'] + env['EXTRA_LIBS']

if env['install']:
    liblucious = env.Install(os.path.join(env['install_path'], "lib"),
        liblucious)

env['LUCIOUS_LIBS'] = lucious_libs

# create the programs
programs = []

programs.extend(SConscript('lucious/SConscript',    exports='env'))
programs.extend(SConscript('benchmarks/SConscript', exports='env'))

for program in programs:
    env.Depends(program, liblucious)

# install it all
if env['install']:
    installed   = []
    executables = []

    print 'Installing Lucious'

    for program in programs:
        executables.append(env.Install(
            os.path.join(env['install_path'], "bin"), program))

    # install headers
    header_directories = [os.path.join(i, 'interface') for i in directories]
    header_extensions = ['*.h']

    headers = []
    for dir in header_directories:
        for ext in header_extensions:
            regexp = os.path.join(dir, ext)
            headers.extend(env.Glob(regexp))

    for header in headers:
        (directoryPath, headerName) = os.path.split( \
            os.path.relpath(str(header), env['path_to_root_dir']))
        installed.append(env.Install(os.path.join( \
            env['install_path'], "include", directoryPath), header))

    # set permissions
    for i in executables:
        env.AddPostAction(i, Chmod(i, 0755))
    for i in installed:
        env.AddPostAction(i, Chmod(i, 0644))

    # Run the install rules by default
    install_alias = env.Alias('install', env['install_path'])
    Default(install_alias)




